"""add gpt_annatation

Revision ID: 674bc5f251e0
Revises: 3521a62ccf0f
Create Date: 2026-07-19 10:01:31.137433

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "674bc5f251e0"
down_revision: Union[str, Sequence[str], None] = "3521a62ccf0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gpt_annotations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("raw_input_id", sa.Integer(), nullable=False),
        sa.Column("transcribed_text", sa.String(), nullable=False),
        sa.Column("extracted_intent", sa.String(), nullable=False),
        sa.Column("extracted_keywords", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["raw_input_id"],
            ["raw_inputs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gpt_annotations")
    # ### end Alembic commands ###
